eno=int(input("Enter employ number"))
ename=input("Enter employ name")
job=input("Enter job")
sal=float(input("Enter salary"))
dno=int(input("Enter department no"))

print("The employ details are...")
print("Eno=",eno)
print("Ename=",ename)
print("Job=",job)
print("Sal=",sal)
print("Dno=",dno)
